package com.github.muraweb;

import javax.persistence.*;

/**
 * Represents a single analysis performed by MuRa.
 */
@Entity
@Table(name = "analysis")
public class Analysis {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    private Integer id;

    /**
     * The link to the GitHub repository.
     */
    private String gitRepo;

    /**
     * Path to the report file generated by MuRa.
     */
    private String report;

    /**
     * Path to the mutants file generated by MuRa.
     */
    private String mutants;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGitRepo() {
        return gitRepo;
    }

    public void setGitRepo(String gitRepo) {
        this.gitRepo = gitRepo;
    }

    public String getReport() {
        return report;
    }

    public void setReport(String report) {
        this.report = report;
    }

    public String getMutants() {
        return mutants;
    }

    public void setMutants(String mutants) {
        this.mutants = mutants;
    }
}
